// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgsamdpiutqubmczpvdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnc2FtZHBpdXRxdWJtY3pwdmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzAxNDYsImV4cCI6MjA2MzQwNjE0Nn0.X-uGuz4M4wblgRvqy6xB5PAakSwrFD62nlh-026_KIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);